version: '3.8'

services:
  app:
    image: ungerardo/yotify:latest
    ports:
      - "3000:3000"
    volumes:
      - /home/{user}/yotify/spotdl_music:/app/spotdl_music
      - /home/{user}/yotify/playlist_files:/app/playlist_files
    environment:
      - PORT=3000
      - SPOTIFY_CLIENT_ID=0000000000000
      - SPOTIFY_CLIENT_SECRET=000000000000
      - SPOTIFY_REDIRECT_URI=http://127.0.0.1:3000/getUserTracks
      - SPOTDL_PATH=/spotdl_music
      - PLAYLIST_FILES_PATH=/playlist_files
      - SPOTDL_TRACK_FORMAT=mp3
      - SPOTDL_TRACK_OUTPUT={artist}/{artist} - {title}.{output-ext}
      - DOWNLOAD_THREADS=1